### ISSUE TITLE
Something here feels kinda wrong, but I do not what

### ISSUE THREAD

**Issue by Yocker64** [haimamire/odin-landing-page#1]
I would say the lack of neofetch in this project is unforgivable, and I cannot believe the lack of updates to this site. I used to be a loyal neofetch enjoyer, but lately, because of the lack of updates; I think I will have to look for an alternative for this page.

**Comment by haimamire** [comment]
Thank you for your feedback!

It sounds like you're passionate about using Neofetch, and we appreciate your past support. While this project may not rely on frequent updates, we aim to keep it stable and functional. If you have specific ideas or features you'd like to see implemented, please feel free to share them or open a pull request.

Your input helps us improve, and we’re always open to collaboration!
